[build]
  command = "npm run build"
  publish = "build"

  [build.environment]
    CI = "false"
    NODE_VERSION = "18"

# SPA fallback (alternative to public/_redirects)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
